name = input("please enter your name: ")
print("\nwelcome to Python, " + name +"!")
print("The type of the variable name is", type(name))
age = input("\nEnter your age: ")
age = int(age)
print("\nYour age is ", age)
print("The type of the variable age is", type(age))