#Fibonacci number is a sequence of numbers that is generated by the sum of the last two numbers of the sequence. Starting with two initial numbers 0 and 1, 
# the next number in sequence is 1 (0 + 1), followed by 2 (1 + 1), followed by 3 (1 + 2), and so on. Therefore, the sequence would look as follows: 
#0, 1, 1, 2, 3, 5, 8, 13, … 
#Let F(n) be the nth number in Fibonacci sequence. Then, F(1) = 0, F(2) = 1, …, F(8) = 13, ... (or F(1) = 0, F(2) = 1, and F(k) = F(k-1) + F(k-2) for k > 1). 
#To make it less trivial, we introduce a modified Fibonacci sequence where MF(1) = 0, MF(2) = 1, and MF(k) = MF(k-1)1/2 + MF(k-2)1.1 for k>1. 
#Your task for module 1 is to write a code that prints the modified Fibonacci sequence of one hundred numbers using Python. 
def Fibonacci(n):

    if n<1:
        print("Incorrect input")
    # instantiating an array to hold previous values so we can build our result on it
    results = []

    # store and print results for k = 0,1 since MF(1)=0, MF(2)=1,

    results.append(0)
    results.append(0)
    print("f(1) is %d" % (results[1]))
    results.append(1)
    print("f(2) is %d" % (results[2]))

    for x in range(3, n+1):
        x1 = results[x-1]
        x2 = results[x-2]
        temp = pow(x1,0.5)+pow(x2,1.1)
        results.append(temp)
        print("f(%d) is %.2f" % (x,results[x]))

# Driver Program
Fibonacci(100)
