#Fibonacci using recursion method
#Fibonacci number is a sequence of numbers that is generated by the sum of the last two numbers of the sequence. Starting with two initial numbers 0 and 1, 
# the next number in sequence is 1 (0 + 1), followed by 2 (1 + 1), followed by 3 (1 + 2), and so on. Therefore, the sequence would look as follows: 
#0, 1, 1, 2, 3, 5, 8, 13, … 
#Let F(n) be the nth number in Fibonacci sequence. Then, F(1) = 0, F(2) = 1, …, F(8) = 13, ... (or F(1) = 0, F(2) = 1, and F(k) = F(k-1) + F(k-2) for k > 1). 
#To make it less trivial, we introduce a modified Fibonacci sequence where MF(1) = 0, MF(2) = 1, and MF(k) = MF(k-1)1/2 + MF(k-2)1.1 for k>1. 
#Your task for module 1 is to write a code that prints the modified Fibonacci sequence of one hundred numbers using Python. 

def Fibonacci_recursion(n):
    print(n)
    if n < 1:
        print("Number entered should be greater than 1")
        return n

    if n < 2:
        return n
    return float(pow(Fibonacci_recursion(n-1),0.5) + pow(Fibonacci_recursion(n-2),1.1))

#Main program
Fibonacci_recursion(3)
#print(temp)
